const TaskActionTypes = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  SEARCH_TASK: 'SEARCH_TASK',
  FETCH_TASK: 'FETCH_TASK',
  FETCH_TASKS: 'FETCH_TASKS',
  FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
  ACTION_FAILURE: 'ACTION_FAILURE',
  ACTION_SUCCESS: 'ACTION_SUCCESS',
  TASK_UPDATED: 'TASK_UPDATED',
};

export default TaskActionTypes;