const TASK_DATA = [
  {
    id: 1,
    name: 'Decide on the components',
    notes: '',
    datetime: '2019-12-23 18:00',
    set_reminder: true,
    is_done: true,
    creator_id: 1,
    category_id: 1,
    priority: 1,
  },
  {
    id: 2,
    name: 'Develop CRUD functionality',
    notes: '',
    datetime: '2019-12-24 18:00',
    set_reminder: true,
    is_done: false,
    creator_id: 1,
    category_id: 1,
    priority: 1,
  },
  {
    id: 3,
    name: 'Implement search and filter functionality',
    notes: '',
    datetime: '2019-12-26 18:00',
    set_reminder: true,
    is_done: false,
    creator_id: 1,
    category_id: 1,
    priority: 1,
  },
  {
    id: 4,
    name: 'Connect to Rails backend',
    notes: '',
    datetime: '2019-12-28 18:00',
    set_reminder: true,
    is_done: false,
    creator_id: 1,
    category_id: 1,
    priority: 1,
  },
  {
    id: 5,
    name: 'Test and finetune app',
    notes: '',
    datetime: '2019-12-29 18:00',
    set_reminder: true,
    is_done: false,
    creator_id: 1,
    category_id: 1,
    priority: 1,
  },
]

export default TASK_DATA;